// Generated by scripts/generate_players.py. Edit config/players.json.
#pragma once
#include <stdint.h>
#include <string.h>
namespace ball {
constexpr uint8_t MASTER = 1, COUNT = 8;
struct Player { uint8_t id; const char* name; uint8_t mac[6]; uint8_t left, right; };
static const Player players[COUNT] = {
  {1, "Ramya G", {0x02,0x00,0x00,0x00,0x00,0x01}, 0, 0},
  {2, "Jyothi.K", {0x02,0x00,0x00,0x00,0x00,0x02}, 0, 3},
  {3, "ABHISHEK KUMAR", {0x02,0x00,0x00,0x00,0x00,0x03}, 2, 4},
  {4, "Durgamani R", {0x02,0x00,0x00,0x00,0x00,0x04}, 3, 5},
  {5, "Shreesathya", {0x02,0x00,0x00,0x00,0x00,0x05}, 4, 6},
  {6, "Sowjanya N", {0x02,0x00,0x00,0x00,0x00,0x06}, 5, 7},
  {7, "Rishab Kumar Kannaujia", {0x02,0x00,0x00,0x00,0x00,0x07}, 6, 8},
  {8, "Sanjeevini", {0x02,0x00,0x00,0x00,0x00,0x08}, 7, 0}
};
inline const Player* findPlayerByID(uint8_t id) { return id >= 1 && id <= COUNT ? &players[id-1] : nullptr; }
inline uint8_t findPlayerByMAC(const uint8_t* mac) {
  for (const auto& p : players) if (memcmp(p.mac, mac, 6) == 0) return p.id;
  return 0;
}
inline uint8_t getLeftNeighbor(uint8_t id) { auto p = findPlayerByID(id); return p ? p->left : 0; }
inline uint8_t getRightNeighbor(uint8_t id) { auto p = findPlayerByID(id); return p ? p->right : 0; }
inline bool adjacent(uint8_t a, uint8_t b) { return a > MASTER && b > MASTER && (getLeftNeighbor(a) == b || getRightNeighbor(a) == b); }
}
