"""Validate the central topology and generate firmware/browser configuration."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
(ROOT / "dashboard").mkdir(exist_ok=True)
(ROOT / "firmware/VirtualBall").mkdir(parents=True, exist_ok=True)
players = json.loads((ROOT / "config/players.json").read_text(encoding="utf-8"))
assert [p["id"] for p in players] == list(range(1, 9)), "Keep IDs 1..8; change links to reorder"
assert players[0]["role"] == "MASTER"
assert all(p["role"] == "SLAVE" for p in players[1:])
assert len({p["mac"].upper() for p in players}) == 8
assert players[0]["left"] == players[0]["right"] == 0
for p in players:
    octets = p["mac"].split(":")
    assert len(octets) == 6 and all(len(x) == 2 and 0 <= int(x, 16) <= 255 for x in octets)
    for side, opposite in (("left", "right"), ("right", "left")):
        n = p[side]
        assert n == 0 or (2 <= n <= 8 and n != p["id"] and players[n-1][opposite] == p["id"])
ends = [p for p in players[1:] if p["left"] == 0]
assert len(ends) == 1
order = []
cursor = ends[0]["id"]
while cursor:
    assert cursor not in order, "Cycle in chain"
    order.append(cursor)
    cursor = players[cursor-1]["right"]
assert len(order) == 7, "All slaves must form one chain"
rows = []
for p in players:
    mac = ",".join("0x" + x for x in p["mac"].split(":"))
    rows.append('  {%d, %s, {%s}, %d, %d}' % (p['id'], json.dumps(p['name']), mac, p['left'], p['right']))
header = '''// Generated by scripts/generate_players.py. Edit config/players.json.
#pragma once
#include <stdint.h>
#include <string.h>
namespace ball {
constexpr uint8_t MASTER = 1, COUNT = 8;
struct Player { uint8_t id; const char* name; uint8_t mac[6]; uint8_t left, right; };
static const Player players[COUNT] = {
''' + ",\n".join(rows) + '''
};
inline const Player* findPlayerByID(uint8_t id) { return id >= 1 && id <= COUNT ? &players[id-1] : nullptr; }
inline uint8_t findPlayerByMAC(const uint8_t* mac) {
  for (const auto& p : players) if (memcmp(p.mac, mac, 6) == 0) return p.id;
  return 0;
}
inline uint8_t getLeftNeighbor(uint8_t id) { auto p = findPlayerByID(id); return p ? p->left : 0; }
inline uint8_t getRightNeighbor(uint8_t id) { auto p = findPlayerByID(id); return p ? p->right : 0; }
inline bool adjacent(uint8_t a, uint8_t b) { return a > MASTER && b > MASTER && (getLeftNeighbor(a) == b || getRightNeighbor(a) == b); }
}
'''
(ROOT / "firmware/VirtualBall/players.h").write_text(header, encoding="utf-8")
(ROOT / "dashboard/players.js").write_text("// Generated; edit config/players.json\nwindow.PLAYERS = " + json.dumps(players, indent=2) + ";\n", encoding="utf-8")
print("Generated firmware and dashboard configuration; chain:", order)
